//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tpv.Backend.Models
{    
    public partial class customer_offers
    {
        public int id_customer_offers { get; set; }
        public int id_customer { get; set; }
        public int id_offer { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual offer offer { get; set; }
    }
}
