//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tpv.Backend.Models
{
    public partial class role_permissions
    {
        public int id_role_permissions { get; set; }
        public int id_role { get; set; }
        public int id_permission { get; set; }
    
        public virtual permission permission { get; set; }
        public virtual role role { get; set; }
    }
}
