//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tpv.Backend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tpvEntities : DbContext
    {
        public tpvEntities()
            : base("name=tpvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<customer_offers> customer_offers { get; set; }
        public virtual DbSet<location> location { get; set; }
        public virtual DbSet<offer> offer { get; set; }
        public virtual DbSet<permission> permission { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<role_permissions> role_permissions { get; set; }
        public virtual DbSet<sale> sale { get; set; }
        public virtual DbSet<sale_details> sale_details { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
